# Generated by Django 5.0.7 on 2024-08-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeachHouseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='no_of_guests',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='inventory',
            field=models.SmallIntegerField(),
        ),
    ]
