# Generated by Django 5.0.7 on 2024-08-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeachHouseApp', '0002_alter_booking_no_of_guests_alter_menu_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
